### ISSUE TITLE
step02.sbatch Folder Name Error

### ISSUE THREAD

**Issue by MaggieEStraight** [blindner6/CEE6720_BIO6720#2]
In step02.sbatch, the example text reads:

# Example:
# sbatch --export input=01_trimmed_reads/2010-winter.1.fastq,output=02_nonpareil_results/2010-winter step02.sbatch

However, I believe the output folder that exists is "02_nonpareil_outputs".
Code seemed to work well when I used this folder name.
*I am characterizing this as a potential problem only as I am very new to this and may have missed a component.

**Comment by bglindner** [comment]
Hey Maggie,

Thanks for creating an issue! I just checked this and you're right. I will edit that in the `lab02.sbatch` script so that the example text is correct.

Blake
